### ISSUE TITLE
Automatically grab scheme manager definition

### ISSUE THREAD

**Issue by confiks** [privacybydesign/attribute-index#3]
As it is now, you have to manually clone or copy the scheme manager definition files into the `attribute-index` project directory to work with `update.py`. Furthermore, when a scheme manager updates, you have to manually update those same scheme manager folders to the latest version. The attribute index obliviously links to the master version of the scheme manager on Github.

Which way would be best to automatically use the latest version of the scheme manager? I see three options, of which I think the first would be best and the easiest to implement:

* Instead of reading files from the filesystem, `update.py` reads all scheme manager XML files directly from Github or privacybydesign.foundation. 
* `update.py` automatically clones (or updates) the scheme manager definitions when invoked, then continues operations as is currently.
* The `attribute-index` repository contains the scheme manager definitions as submodules, which must be manually updated.

**Comment by aykevl** [comment]
The first option would make things a lot more complicated, I think. I don't think it is possible to get a directory listing on the privavybydesign.foundation website and I'm not aware of a way to do it on GitHub but it's probably a bit more difficult (but possible).

I think it is best to update the scheme managers on each update. That's how I originally intended it, I simply haven't written the code. This can be done from Python but maybe it's easier to write a Makefile. What do you think about using `make`?

I don't think submodules are a good idea: then an update to the attribute index is needed on each scheme managers update (submodules are based on commits, not branches).

**Comment by confiks** [comment]
So I think this feature is out of scope for this project.
