### ISSUE TITLE
Show a deprecation warning

### ISSUE THREAD

**Issue by stefanvermaas** [privacybydesign/attribute-index#7]
Whenever an attribute gets deprecated, it would be great to have this fact be reflected on the documentation site. Currently, the only way to find out is by looking at the implementation or by experiencing it's deprecated while implementing it. 

Also see; https://github.com/privacybydesign/pbdf-schememanager/pull/52#issuecomment-767419475

**Comment by sietseringers** [comment]
Thanks, you're right. This should indeed certainly be shown here. We'll add that in an upcoming version.
